// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKhZQrVT2YURp8-4rB0whQSUrnLE84go',
    appId: '1:711096347122:web:4896a29246c1ac19e3a36b',
    messagingSenderId: '711096347122',
    projectId: 'sabail',
    authDomain: 'sabail.firebaseapp.com',
    storageBucket: 'sabail.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuWpEyVf0WsCbvQggM10SD_sm9o_MK-w',
    appId: '1:711096347122:android:293d20a5e3019f29e3a36b',
    messagingSenderId: '711096347122',
    projectId: 'sabail',
    storageBucket: 'sabail.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiGmOZAdsq5eMXZqqow-v2yPjkLNlq_uA',
    appId: '1:711096347122:ios:6494f1ebc22b03cfe3a36b',
    messagingSenderId: '711096347122',
    projectId: 'sabail',
    storageBucket: 'sabail.firebasestorage.app',
    iosBundleId: 'com.example.sabail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiGmOZAdsq5eMXZqqow-v2yPjkLNlq_uA',
    appId: '1:711096347122:ios:6494f1ebc22b03cfe3a36b',
    messagingSenderId: '711096347122',
    projectId: 'sabail',
    storageBucket: 'sabail.firebasestorage.app',
    iosBundleId: 'com.example.sabail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQKhZQrVT2YURp8-4rB0whQSUrnLE84go',
    appId: '1:711096347122:web:324e93901884480be3a36b',
    messagingSenderId: '711096347122',
    projectId: 'sabail',
    authDomain: 'sabail.firebaseapp.com',
    storageBucket: 'sabail.firebasestorage.app',
  );
}
